### ISSUE TITLE
Use the React Hooks API

### ISSUE THREAD

**Issue by joepio** [fletcher91/link-redux#11]
The `mapDataToProps` provides a useful and easy way to map specific RDF properties to local JS representations. However, this requires that a component is registered to LRS, and it is wrapped in a register call.

The recently added [React Hooks API](https://reactjs.org/docs/hooks-intro.html) introdcuces a clean way to get dynamic data in React components. I think this might be a useful and intuitive API to use in this project.

A custom Link-Redux hook could look something like this:

``` jsx
function BlogPreview(props) {
  const title = useProp(props.subject, "https://shema.org/title");
  const intro = useProp(props.subject, "https://example.com/ns/articleIntro");

  return (
    <article>
      <h1>{title}</h1>
      <p>{intro}</p>
    </article>
  );
}
```

The returned type depends on the object value of the RDF triple (IRI, string, number).
Perhaps we could store the RDF triple 

Other hooks might be useful as well:

- Getting the (first) parent subject `useSubject()`
- Getting the topology `useTopology()`

What do you think, @fletcher91? Does this fit in this project, or should it be a different library altogether?

**Comment by fletcher91** [comment]
There already are a lot of hooks in the project but are still prone to change, e.g. the [`useLinkRenderContext`](https://github.com/fletcher91/link-redux/blob/master/src/hocs/withLinkCtx.tsx#L29) hook which gives access to both the subject and the topology.

Something like `useProp` doesn't seem feasible since there are a lot of edge cases to cover with regards to fetching, updating, and normalization. It's likely that `useMapDataToProps` would be a future addition
