### ISSUE TITLE
Component for listing other props

### ISSUE THREAD

**Issue by joepio** [fletcher91/link-redux#5]
Currently, the props that are rendered need to be specified. I feel like this tool would be more powerful if it could also render all the properties of a resource that do not yet have a know view.

In order for this to be possible, a couple of things need to change:

* There should be a generic property view. I suggest that the default component prints the predicate and the object. If some `rdf:label` of the predicate is known, render that instead to increase readability. Users could overwrite this view by registering their own DefaultProp component.
* ~~The state should know which props are being rendered to prevent duplicate renders.~~ Use an `ignore` prop to le the component know which properties are rendered somewhere else to prevent duplicate renders.

**Comment by fletcher91** [comment]
You can already render properties that do not have a view (`Property` will just render the value in a div).

Technically, a component could be registered for `rdf:Property`, which acts as the superclass for all property types. The current reasoner doesn't infer this relation though.

While the added value of some sort of bucket system is evident, this might cause significant computing resources to implement, since all the property references within each object context will need to be counted.  Turning the system on only when a component uses this feature, and/or checking the children in advance to see if one of them uses the bucket might help in optimization though.

**Comment by joepsz** [comment]
I've got a different idea for preventing duplicate renders: add an optional `ignore` prop, which contains all the properties that are rendered somewhere else.

**Comment by fletcher91** [comment]
This currently isn't properly implementable (too many edge-cases/manual intervention needed).

This issue might be reopened later when a general, efficient, and automatable solution has been found.
